# justfile

localize:
    yarn
    node Scripts/generateLocales.js

bump-version:
    go run Scripts/xcode-app-version-bumper/*go

clear-mac-data:
    rm -rf ~/Library/Containers/{{cookiecutter.app_identifier}}
    echo "Cleared Mac data"

format:
    swiftformat .

# acknowledgements:
#     python3 Scripts/xcode-acknowledgements/main.py --scheme Tasktive --output Modules/SettingsUI/Sources/SettingsUI/Resources