# justfile

localize:
    yarn
    node Scripts/generateLocales.js

bump-version:
    go run Scripts/xcode-app-version-bumper/*go

clear-mac-data:
    rm -rf ~/Library/Containers/{{cookiecutter.app_identifier}}
    echo "Cleared Mac data"

format:
    swiftformat .

acknowledgements:
    python3 Scripts/xcode-acknowledgements/main.py --scheme {{cookiecutter.app_name}} --output {{cookiecutter.app_name}}/Resources

generate:
    just acknowledgements
    just localize

build:
    #!/bin/sh

    just generate

    CONFIGURATION="Debug"
    WORKSPACE="{{cookiecutter.app_name}}.xcworkspace"
    SCHEME="{{cookiecutter.app_name}}"

    # set -o pipefail && xcodebuild -configuration $CONFIGURATION -workspace $WORKSPACE -scheme $SCHEME -destination $DESTINATION | xcpretty
    xcodebuild -configuration $CONFIGURATION -workspace $WORKSPACE -scheme $SCHEME -destination $DESTINATION
